### ISSUE TITLE
CGI proxy on scooby server required to access Maxent output

### ISSUE THREAD

**Issue by achmurzy** [EnquistLab/ffdm-frontend#1]
I will try to write my own but if you guys have the hold CGI proxy laying around you can edit your credentials out and I'll gladly fill in my own for scooby

**Comment by achmurzy** [comment]
@npcasler 
@dguaderrama

**Comment by npcasler** [comment]
I don't have access to the machine, but the cgi is a basic script to change urls to file pathnames. The files should be located in /var/www/data if my memory serves me correctly.

**Comment by achmurzy** [comment]
I found it on scooby, thanks Nathan
